# docker-compose.yaml
# 同样遵循严格的缩进
version: '3.1'

# services 定义容器列表
services:
    consignment-cli:
        build: ./consignment-cli
        environment:
            MICRO_REGISTRY: "mdns"

    consignment-service:
        build: ./consignment-service
        ports:
            - 50051:50051
        environment:
            MICRO_ADRESS: ":50051"
            MICRO_REGISTRY: "mdns"
            DB_HOST: "datastore:27017"
            DISABLE_AUTH: "false"
        depends_on: 
            - datastore

    vessel-service:
        build: ./vessel-service
        ports:
            - 50052:50051
        environment:
            MICRO_ADRESS: ":50051"
            MICRO_REGISTRY: "mdns"
            DB_HOST: "datastore:27017"
        depends_on: 
            - datastore

    user-service:
        build: ./user-service
        ports:
            - 50053:50051
        environment:
            MICRO_ADRESS: ":50051"
            MICRO_REGISTRY: "mdns"
            DB_NAME: "userServiceDB"
            DB_HOST: "database"
            DB_PORT: "3306"
            DB_USER: "userService"
            DB_PASSWORD: "12345"
        depends_on:
            - database

    user-cli:
        build: ./user-cli
        environment:
            MICRO_REGISTRY: "mdns"

    email-service:
        build: ./email-service
        ports: 
            - 50054:50051
        environment: 
            MICRO_REGISTRY: "mdns"
    
    nats:
        image: nats
        ports:
            - "4222:4222"

    datastore:
        image: mongo
        ports: 
            - "27017:27017"

    database:
        image: mysql
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: "66666"
            MYSQL_USER: "userService"
            MYSQL_PASSWORD: "12345"
            MYSQL_DATABASE: "userServiceDB"